#!/usr/bin/env bash
# Regenerates src/stations.rs from the official 1BRC data generator.
# Run once; the output is committed.
set -euo pipefail

URL="https://raw.githubusercontent.com/gunnarmorling/1brc/main/src/main/java/dev/morling/onebrc/CreateMeasurements.java"
OUT="$(cd "$(dirname "$0")/.." && pwd)/src/stations.rs"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
curl -sSL "$URL" -o "$tmp"

count="$(grep -c 'new WeatherStation(' "$tmp")"
if [ "$count" -lt 400 ]; then
    echo "error: only found $count stations, upstream format probably changed" >&2
    exit 1
fi

{
    echo "// @generated by scripts/gen_stations.sh -- do not edit by hand."
    echo "// Source: CreateMeasurements.java, github.com/gunnarmorling/1brc"
    echo "//"
    echo "// Mean temperature per station; the generator samples a gaussian with sigma = 10"
    echo "// around each mean."
    echo
    echo "pub const STATIONS: &[(&str, f64)] = &["
    grep -o 'new WeatherStation("[^"]*", *-\?[0-9.]*)' "$tmp" \
        | sed -E 's/new WeatherStation\("([^"]*)", *(-?[0-9.]+)\)/    ("\1", \2),/'
    echo "];"
} >"$OUT"

echo "wrote $count stations to $OUT"
